/**:
  controller_manager:
    ros__parameters:
      update_rate: 100

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      drive_controller:
        type: diff_drive_controller/DiffDriveController
      
      imu_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster
  
  imu_broadcaster:
    ros__parameters:
      sensor_name: <namespace>/imu
      frame_id: <namespace>/imu_link
      static_covariance_orientation: [1.8e-3, 0.0, 0.0, 0.0, 1.8e-3, 0.0, 0.0, 0.0, 1.8e-3]
      static_covariance_angular_velocity: [1.0e-4, 0.0, 0.0, 0.0, 1.0e-4, 0.0, 0.0, 0.0, 1.0e-4]
      static_covariance_linear_acceleration: [7.6e-4, 0.0, 0.0, 0.0, 7.6e-4, 0.0, 0.0, 0.0, 7.6e-4]

  drive_controller:
    ros__parameters:
      left_wheel_names: [fl_wheel_base_to_fl_wheel_joint, rl_wheel_base_to_rl_wheel_joint]
      right_wheel_names: [fr_wheel_base_to_fr_wheel_joint, rr_wheel_base_to_rr_wheel_joint]

      wheel_separation: 0.626
      wheel_radius: 0.1651

      wheel_separation_multiplier: 1.0

      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0

      publish_rate: 100.0
      odom_frame_id: odom
      base_frame_id: base_link
      twist_covariance_diagonal: [5.4e-5, 5.4e-5, 0.0, 0.0, 0.0, 1.9e-4]

      open_loop: true

      position_feedback: false
      velocity_rolling_window_size: 1

      enable_odom_tf: false

      cmd_vel_timeout: 0.5
      publish_limited_velocity: true

      linear:
        x:
          max_velocity: 2.0 # m/s
          min_velocity: -2.0 # m/s
          max_acceleration: 2.7 # m/s^2
          max_deceleration: -2.7 # m/s^2
          max_acceleration_reverse: -2.7 # m/s^2
          max_deceleration_reverse: 2.7 # m/s^2
          max_jerk: .NAN # m/s^3
          min_jerk: .NAN # m/s^3

      angular:
        z:
          max_velocity: 4.0 # rad/s
          min_velocity: -4.0 # rad/s
          max_acceleration: 5.74 # rad/s^2
          max_deceleration: -5.74 # rad/s^2
          max_acceleration_reverse: -5.74 # rad/s^2
          max_deceleration_reverse: 5.74 # rad/s^2
          max_jerk: .NAN # rad/s^3
          min_jerk: .NAN # rad/s^3